### ISSUE TITLE
【依頼】フリマアプリ挙動確認	

### ISSUE THREAD

**Issue by keeee-a** [keeee-a/furima-30960#12]
# URL
https://furima-30960.herokuapp.com
# Basic認証
ID：admin
パスワード：2222
# 出品者用アカウント
メールアドレス：sample5@sample5
パスワード：aiueo12345
# 購入者用アカウント
メールアドレス：sample6@sample6
パスワード：aiueo12345
# 購入用カード
カード番号：4242424242424242
有効期限：3月23年
セキュリティコード：123

**Comment by techcamp-N** [comment]
@keeee-a さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
○商品詳細ページにて、商品出品時に登録した情報が見られるようにしましょう
（現状、発送日の目安が正しく表示されていません）

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by techcamp-N** [comment]
@keeee-a さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
